// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/transaction_service/v1/transaction.proto

package transaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionSvc_GetTransactions_FullMethodName   = "/proto.transaction_service.v1.TransactionSvc/GetTransactions"
	TransactionSvc_CreateTransaction_FullMethodName = "/proto.transaction_service.v1.TransactionSvc/CreateTransaction"
)

// TransactionSvcClient is the client API for TransactionSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionSvcClient interface {
	GetTransactions(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*MutationTransResponse, error)
}

type transactionSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionSvcClient(cc grpc.ClientConnInterface) TransactionSvcClient {
	return &transactionSvcClient{cc}
}

func (c *transactionSvcClient) GetTransactions(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, TransactionSvc_GetTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionSvcClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*MutationTransResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationTransResponse)
	err := c.cc.Invoke(ctx, TransactionSvc_CreateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionSvcServer is the server API for TransactionSvc service.
// All implementations must embed UnimplementedTransactionSvcServer
// for forward compatibility.
type TransactionSvcServer interface {
	GetTransactions(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	CreateTransaction(context.Context, *CreateTransactionRequest) (*MutationTransResponse, error)
	mustEmbedUnimplementedTransactionSvcServer()
}

// UnimplementedTransactionSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionSvcServer struct{}

func (UnimplementedTransactionSvcServer) GetTransactions(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedTransactionSvcServer) CreateTransaction(context.Context, *CreateTransactionRequest) (*MutationTransResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedTransactionSvcServer) mustEmbedUnimplementedTransactionSvcServer() {}
func (UnimplementedTransactionSvcServer) testEmbeddedByValue()                        {}

// UnsafeTransactionSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionSvcServer will
// result in compilation errors.
type UnsafeTransactionSvcServer interface {
	mustEmbedUnimplementedTransactionSvcServer()
}

func RegisterTransactionSvcServer(s grpc.ServiceRegistrar, srv TransactionSvcServer) {
	// If the following call pancis, it indicates UnimplementedTransactionSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionSvc_ServiceDesc, srv)
}

func _TransactionSvc_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionSvcServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionSvc_GetTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionSvcServer).GetTransactions(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionSvc_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionSvcServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionSvc_CreateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionSvcServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionSvc_ServiceDesc is the grpc.ServiceDesc for TransactionSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.transaction_service.v1.TransactionSvc",
	HandlerType: (*TransactionSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactions",
			Handler:    _TransactionSvc_GetTransactions_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _TransactionSvc_CreateTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction_service/v1/transaction.proto",
}
